### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by azmeuk** [abmyii/geonames#2]
Hi. It seems this package is not hosted on pypi under the `geonames` name. Maybe a typo?

```bash
$ pip install geonames
$ python -c "import geonames"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/azmeuk/env/lib/python3.9/site-packages/geonames/__init__.py", line 22, in <module>
    from .geonames import Geonames
  File "/home/azmeuk/env/lib/python3.9/site-packages/geonames/geonames.py", line 253
    geonames = Geonames('C:\Users\GEO_Admin\Downloads\JM\JM.txt')
                                                                ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

This looks to be a different package

**Comment by abmyii** [comment]
Ah yes, sorry about that. I install it via Git so forgot to change the README instructions.
